### ISSUE TITLE
Issue while cloning a windows certificate

### ISSUE THREAD

**Issue by Ekultek** [optiv/Mangle#9]
```
me@DESKTOP:/path$ mangle -I calc_edit.exe -O new_calc_edit.exe -C windows.storage.dll

           _____                        .__
          /     \ _____    ____    ____ |  |   ____
         /  \ /  \\__  \  /    \  / ___\|  | _/ __ \
        /    Y    \/ __ \|   |  \/ /_/  >  |_\  ___/
        \____|__  (____  /___|  /\___  /|____/\___  >
                \/     \/     \//_____/           \/
                                        (@Tyl0us)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x138 pc=0x4aa29f]

goroutine 1 [running]:
main.Stealer({0xc000136000, 0xa279, 0xa27a}, {0xc000180000, 0x79a9b8, 0x79a9b9})
        /home/me/Mangle/Mangle.go:142 +0x11f
main.main()
        /home/me/Mangle/Mangle.go:83 +0x1f1
me@DESKTOP:/path$
```

Certificate file is attached
[windows.storage.zip](https://github.com/optiv/Mangle/files/9995861/windows.storage.zip)

**Comment by Tylous** [comment]
Hello out of curiosity did you run this multiple times with the same issue? Also could you let me know what OS/version you were running?

**Comment by Ekultek** [comment]
@Tylous hi sorry for the delay, yes I ran it multiple times and it produced the same problem. I'm on Windows 10 using Ubuntu WSL:

uname -a: `Linux DESKTOP 4.4.0-19041-Microsoft #1237-Microsoft Sat Sep 11 14:32:00 PST 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by Tylous** [comment]
Sorry for the delay on my end I think your issue is taking values from a DLL and putting them on .exe
